/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolist.view;

import com.mycompany.todolist.model.Usuario;
import com.mycompany.todolist.util.ConfiguraComponentes;
import com.mycompany.todolist.util.ValidaCampos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Cadastro extends javax.swing.JFrame {

    private ArrayList<Usuario> listaDeUsuarios = new ArrayList<Usuario>();
    private ConfiguraComponentes cf = new ConfiguraComponentes();
    private ValidaCampos validaCampos = new ValidaCampos();
    
    public Cadastro() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); 
        configCampos();
        System.out.println(listaDeUsuarios.toString());
    }
    
    public Cadastro(ArrayList<Usuario> listaDeUsuarios){
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null); 
        this.listaDeUsuarios = listaDeUsuarios;
        configCampos();
        System.out.println(listaDeUsuarios.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeCompleto = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        psfSenha = new javax.swing.JPasswordField();
        psfConfirmarSenha = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbxMostrarSenha = new javax.swing.JCheckBox();
        cbxConfirmarSenha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(201, 186, 170));

        jLabel1.setText("Cadastro");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbxMostrarSenha.setText("Mostrar senha");
        cbxMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMostrarSenhaActionPerformed(evt);
            }
        });

        cbxConfirmarSenha.setText("Mostrar senha");
        cbxConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConfirmarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtNomeCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(psfSenha)
                            .addComponent(psfConfirmarSenha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxMostrarSenha)
                            .addComponent(cbxConfirmarSenha))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMostrarSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psfConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxConfirmarSenha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(validaCampos()){
            Usuario usuario = retornaUsuario();
            listaDeUsuarios.add(usuario);
            System.out.println(listaDeUsuarios.toString());
            new Login(listaDeUsuarios).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMostrarSenhaActionPerformed
        String senha =  String.valueOf(psfSenha.getPassword());
        cf.configCheckBox(cbxMostrarSenha, psfSenha, "Senha", senha );
    }//GEN-LAST:event_cbxMostrarSenhaActionPerformed

    private void cbxConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConfirmarSenhaActionPerformed
        String senha =  String.valueOf(psfSenha.getPassword());
        cf.configCheckBox(cbxConfirmarSenha, psfConfirmarSenha, "Senha", senha );
    }//GEN-LAST:event_cbxConfirmarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JCheckBox cbxConfirmarSenha;
    private javax.swing.JCheckBox cbxMostrarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField psfConfirmarSenha;
    private javax.swing.JPasswordField psfSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCompleto;
    // End of variables declaration//GEN-END:variables

    private void configCampos() {
        cf.configCampoTexto(txtNomeCompleto, "Nome Completo");
        cf.configCampoTexto(txtEmail, "Email"); 
        cf.configCampoSenha(psfSenha, "Senha");
        cf.configCampoSenha(psfConfirmarSenha, "Confirmar senha");
    }
    
    private Usuario retornaUsuario() {
        String email = txtEmail.getText();
        String nome = txtNomeCompleto.getText();
        
        String senha = String.valueOf(psfSenha.getPassword());
        String confirmarSenha = String.valueOf(psfConfirmarSenha.getPassword());

        if (!senha.equals(confirmarSenha)) {
            JOptionPane.showMessageDialog(this, "Erro: as senhas não coincidem!");
            return null; 
        }
        
        Usuario usuario = new Usuario();
        usuario.setEmail(email);
        usuario.setSenha(senha);
        usuario.setNomeCompleto(nome);

        return usuario;
    }    

    private boolean validaCampos(){
        boolean resultado =  true;
        
        if(validaCampos.validaTextField(txtNomeCompleto, "Nome Completo")) resultado = false;
        if(validaCampos.validaTextField(txtEmail, "Email")) resultado = false;
        if(validaCampos.validaPasswordField(psfSenha, "Senha")) resultado = false;
        if(validaCampos.validaPasswordField(psfConfirmarSenha, "Confirmar senha")) resultado = false;
        
        String senha = String.valueOf(psfSenha.getPassword());
        String confirmarSenha = String.valueOf(psfConfirmarSenha.getPassword());
        
        if(!senha.equals(confirmarSenha)) {
            JOptionPane.showMessageDialog(this, "As senhas não coincidem!");
            resultado = false;
        }
        
        return resultado;
    }

}
