/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolist.view;

import com.mycompany.todolist.model.Usuario;
import com.mycompany.todolist.util.ConfiguraComponentes;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Login extends javax.swing.JFrame {

    private final ConfiguraComponentes cf = new ConfiguraComponentes();
    private ArrayList<Usuario> listaDeUsuarios = new ArrayList<Usuario>();
            
    public Login() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); 
        configCampos();
        System.out.println(listaDeUsuarios.toString());
    }
    
    public Login(ArrayList<Usuario> listaDeUsuarios){
        initComponents();
        setResizable(false); 
        setLocationRelativeTo(null); 
        configCampos(); 
        this.listaDeUsuarios = listaDeUsuarios;
        System.out.println(listaDeUsuarios.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        psfSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        cbxMostrarSenha = new javax.swing.JCheckBox();
        lblCliqueAqui = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(201, 186, 170));

        jLabel1.setText("Login");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        cbxMostrarSenha.setText("Mostrar senha");
        cbxMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMostrarSenhaActionPerformed(evt);
            }
        });

        lblCliqueAqui.setForeground(new java.awt.Color(153, 153, 255));
        lblCliqueAqui.setText("Se cadastre aqui");
        lblCliqueAqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCliqueAquiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addComponent(psfSenha))
                    .addComponent(btnEntrar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliqueAqui)
                    .addComponent(cbxMostrarSenha))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMostrarSenha))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(lblCliqueAqui))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        for(int i = 0; i < listaDeUsuarios.size(); i++){
            
            String email = listaDeUsuarios.get(i).getEmail();
            String senha = listaDeUsuarios.get(i).getSenha();
            
            String emailDigitado = txtEmail.getText();
            String senhaDigitada = String.valueOf(psfSenha.getPassword());
            
            if(email.equals(emailDigitado) && senha.equals(senhaDigitada)){
                new Principal().setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Os campos não coincidem");
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void lblCliqueAquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCliqueAquiMouseClicked
        Cadastro cadastro = new Cadastro(listaDeUsuarios);
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCliqueAquiMouseClicked

    private void cbxMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMostrarSenhaActionPerformed
        String senha =  String.valueOf(psfSenha.getPassword());
        cf.configCheckBox(cbxMostrarSenha, psfSenha, "Senha", senha );
    }//GEN-LAST:event_cbxMostrarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox cbxMostrarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCliqueAqui;
    private javax.swing.JPasswordField psfSenha;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
    
    private void configCampos(){
        cf.configCampoTexto(txtEmail, "Email");
        cf.configCampoSenha(psfSenha, "Senha");   
    }   
    
}
